version: "3.9"

services:
  db:
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
    # WARNING : DB **SHOULD NEVER** BE EXPOSED IN THE PROD INSTANCE. Be careful when using the local docker compose.
      - 5432:5432
  backend:
    build:
      context: ./
      dockerfile: ./deploy/backend/Dockerfile
    # image: metlo/backend
    container_name: metlo-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/metlo_api_security
      #- ENCRYPTION_KEY=
      #- BACKEND_URL=
      #- EXPRESS_SECRET=
  jobs:
    image: metlo/jobrunner
    container_name: metlo-jobs
    restart: unless-stopped
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/metlo_api_security
  frontend:
    # image: metlo/frontend
    build:
      context: ./
      dockerfile: ./deploy/frontend/Dockerfile
    container_name: metlo-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - 8000:3000

volumes:
  db:
    driver: local
